In [1]:
from passengers import Passengers, Line

lines = {}

file_name = 'data/t091307.xlsx'
line = '田園都市線'
skip_rows = list(range(0, 11)) + list(range(12, 15))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091306.xlsx'
line = '東横線'
skip_rows = list(range(0, 12)) + list(range(13, 16))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091305.xlsx'
line = '京浜急行線'
skip_rows = list(range(0, 12)) + list(range(13, 16))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091304.xlsx'
line = '相模鉄道線'
skip_rows = list(range(0, 12)) + list(range(13, 16))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091303.xlsx'
line = 'みなとみらい線'
skip_rows = list(range(0, 11)) + list(range(12, 15))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091302.xlsx'
line = '金沢シーサイドライン'
skip_rows = list(range(0, 11)) + list(range(12, 15))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091203.xlsx'
line = 'グリーンライン'
skip_rows = list(range(0, 11)) + list(range(12, 15))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

file_name = 'data/t091202.xlsx'
line = 'ブルーライン'
skip_rows = list(range(0, 11)) + list(range(12, 15))
use_cols = list(range(1, 100))
lines[line] = Line(file_name, line, skip_rows, use_cols)

ps = Passengers()
for line in lines.values():
    ps.read_csv(line=line)
import re
display(ps.passengers.head())

/Users/toh/Documents/GitHub/Yokohama-passengers/passengers.py:57: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  df_sheet = df_sheet.convert_objects(convert_numeric=True)
/Users/toh/Documents/GitHub/Yokohama-passengers/passengers.py:93: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df = pd.concat([df, df_sheet])

skip H19

,あざみ野,いずみ中央,いずみ野,こどもの国,たまプラーザ,みなとみらい,みなとみらい線総数,ゆめが丘,グリーンライン総数,センター北,...,関内,阪東橋,青葉台,馬車道,高島町,高田,鳥浜,鶴ケ峰,鶴見市場,黄金町
2008-05-01,3394026.0,254876.0,243144.0,180451.0,1114264.0,829651.0,4938532.0,27251.0,1932688.0,642684.0,...,709984.0,254787.0,1778253.0,483941.0,101413.0,119953.0,122492.0,907573.0,293515.0,362505.0
2008-06-01,3356863.0,254045.0,240555.0,164730.0,1107780.0,815157.0,4864791.0,27105.0,2111297.0,635755.0,...,696772.0,247872.0,1762350.0,475238.0,99716.0,128558.0,105923.0,896850.0,291525.0,358631.0
2008-07-01,3274373.0,252736.0,233483.0,151528.0,1096439.0,844825.0,4983337.0,26226.0,2156892.0,639628.0,...,718852.0,248880.0,1702055.0,488939.0,101941.0,129924.0,106783.0,887431.0,287329.0,354444.0
2008-08-01,3109425.0,238522.0,229294.0,153481.0,987567.0,874165.0,4990062.0,24738.0,2098696.0,625330.0,...,707670.0,246643.0,1591509.0,478591.0,103712.0,129376.0,120912.0,863961.0,284726.0,340601.0
2008-09-01,3240686.0,238821.0,239541.0,157440.0,1078020.0,811747.0,5005837.0,26249.0,2252524.0,639042.0,...,695431.0,247155.0,1716840.0,482740.0,102150.0,132056.0,109699.0,880686.0,284615.0,354515.0